=== flong2395-cyber/slobbers-store/tienda.dtd
<!ELEMENT tienda (producto+)>

<!ELEMENT producto (nombre, precio, imagen)>
<!ATTLIST producto id CDATA #IMPLIED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>

=== flong2395-cyber/slobbers-store/bisuteria.xml
<?xml version="1.0"?>
<!DOCTYPE tienda SYSTEM "tienda.dtd">
<?xml-stylesheet type="text/xsl" href="tienda.xsl"?>

<tienda>
    
    <producto>
        <nombre>Chain Punk</nombre>
        <precio>25</precio>
        <imagen>img/art1.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Cyber Ring</nombre>
        <precio>15</precio>
        <imagen>img/art2.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Neon Chain</nombre>
        <precio>30</precio>
        <imagen>img/art3.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Dark Bracelet</nombre>
        <precio>20</precio>
        <imagen>img/art4.jpg</imagen>
    </producto>
    
</tienda>

=== flong2395-cyber/slobbers-store/hombre.xml
<?xml version="1.0"?>
<!DOCTYPE tienda SYSTEM "tienda.dtd">
<?xml-stylesheet type="text/xsl" href="tienda.xsl"?>

<tienda>
    
    <producto>
        <nombre>Cyber Jacket</nombre>
        <precio>120</precio>
        <imagen>img/hombre1.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Punk Hoodie</nombre>
        <precio>80</precio>
        <imagen>img/hombre2.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Urban Tech Coat</nombre>
        <precio>140</precio>
        <imagen>img/hombre3.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Dark Street Fit</nombre>
        <precio>95</precio>
        <imagen>img/hombre4.jpg</imagen>
    </producto>
    
</tienda>

=== flong2395-cyber/slobbers-store/mujer.xml
<?xml version="1.0"?>
<!DOCTYPE tienda SYSTEM "tienda.dtd">
<?xml-stylesheet type="text/xsl" href="tienda.xsl"?>

<tienda>
    
    <producto>
        <nombre>Cyber Dress</nombre>
        <precio>70</precio>
        <imagen>img/mujer1.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Neon Jacket</nombre>
        <precio>120</precio>
        <imagen>img/mujer2.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Dark Outfit</nombre>
        <precio>95</precio>
        <imagen>img/mujer3.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Future Style Set</nombre>
        <precio>110</precio>
        <imagen>img/mujer4.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
    <producto>
        <nombre>Articulo</nombre>
        <precio>0</precio>
        <imagen>img/articulo.jpg</imagen>
    </producto>
    
</tienda>
